name: CI Pipeline

on:
  release:
    types:
      - created

env:
  AWS_REGION: us-east-1              
  ECR_REPOSITORY: b4c0c6w7/tesis/tp1-frontend

permissions:
  contents: read # por detras, el runner utiliza un token para autenticarse contra Actions, esta linea especifica los permisos de dicho token, en este caso, leer

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # define la imagen del runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # esta action descarga el repositorio en el runner para ser leido. V4 esta especificando la version del 
                                  # action usado, para que siga funcionando en caso de que se introduzcan breaking changes

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.3.1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: public

      - name: Build, tag, and push docker image to Amazon ECR Public
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: ${{ env.ECR_REPOSITORY }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -f docker-config/Dockerfile -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

